In [1]:
import pandas as pd

In [2]:
#https://github.com/codebasics/py/blob/master/ML/14_naive_bayes/14_naive_bayes_1_titanic_survival_prediction.ipynb

In [3]:
df= pd.read_csv(r"C:\Users\adity\OneDrive\Desktop\ML\titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [6]:
target = df.Survived

In [7]:
input = df.drop('Survived', axis='columns')

In [9]:
dummies = pd.get_dummies(input.Sex).astype(int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       0     1

In [10]:
input= pd.concat([input , dummies],axis ='columns')
input.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  34.5   7.8292       0     1
1       3  female  47.0   7.0000       1     0
2       2    male  62.0   9.6875       0     1
3       3    male  27.0   8.6625       0     1
4       3  female  22.0  12.2875       1     0

In [11]:
input=input.drop('Sex',axis='columns')

In [12]:
input.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [40]:
input.isna().sum()

Pclass    0
Age       0
Fare      0
female    0
dtype: int64

In [41]:
input['Age']=input['Age'].fillna(input.Age.mean())

In [42]:
input['Fare']=input['Fare'].fillna(input.Fare.mean())

In [43]:
input.head(10)

   Pclass   Age     Fare  female
0       3  34.5   7.8292       0
1       3  47.0   7.0000       1
2       2  62.0   9.6875       0
3       3  27.0   8.6625       0
4       3  22.0  12.2875       1
5       3  14.0   9.2250       0
6       3  30.0   7.6292       1
7       2  26.0  29.0000       0
8       3  18.0   7.2292       1
9       3  21.0  24.1500       0

In [44]:
input=input.drop('male',axis='columns')

KeyError: "['male'] not found in axis"

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(input,target,test_size=0.3)

In [47]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [48]:
model.fit(X_train , y_train)

GaussianNB()

In [49]:
model.score(X_test , y_test)

1.0